cmake_minimum_required(VERSION 3.13)
find_package(deal.II 9.0 REQUIRED HINTS ${DEAL_II_DIR})
deal_ii_initialize_cached_variables()
project(solver)
add_executable(solver solver.cc)
deal_ii_setup_target(solver)
